[package]
name = "fashion-mnist"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { workspace = true }
tokio = {workspace = true }
serde = {workspace = true}
plotters = { workspace = true }
plotters-backend = { workspace = true }
