[package]
name = "gradient-descent"
version = "0.1.0"
edition = "2021"

[dependencies]
burn     = { workspace = true }
plotters = { workspace = true }
serde    = { workspace = true }
csv      = { workspace = true }
anyhow   = { workspace = true }