[package]
name = "perceptron-algorithm"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
ndarray = { version = "0.16.1", default-features = false }
ndarray-rand = "0.15.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
plotters = "0.3.7"

[profile.dev]
panic = 'abort'
strip = true
